spring:
  application:
    name: spring-boot-postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
